version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pa55w0rd
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
