### Get books
GET http://localhost:5035/api/v1/books

### Get a book by ISBN
GET http://localhost:5035/api/v1/books/9781617296284

### Create a book
POST http://localhost:5035/api/v1/books
Content-Type: application/json

{
  "isbn": "9781617296284",
  "title": "Desiging APIs with Swagger and OpenAPI",
  "year": "2002"
}

### Remove a book
DELETE http://localhost:5035/api/v1/books/9781617296284

### Update a book
PUT http://localhost:5035/api/v1/books/9781617296284
Content-Type: application/json

{
  "isbn": "9781617296284",
  "title": "Designing APIs with Swagger and OpenAPI",
  "year": "2022"
}

### Partial Update
PATCH http://localhost:5035/api/v1/books/9781617296284
Content-Type: application/json

{
  "year": "2022"
}