### Get books
GET http://localhost:5035/api/v1/books

### Get a book by id
GET http://localhost:5035/api/v1/books/1

### Create a book
POST http://localhost:5035/api/v1/books
Content-Type: application/json

{
  "title": "EF Core in Action",
  "year": 2021,
  "topic": "Software Engineering",
  "author": "John Smith"
}

### Remove a book
DELETE http://localhost:5035/api/v1/books/1

### Update a book
PUT http://localhost:5035/api/v1/books/9834
Content-Type: application/json

{
  "title": "EF Core in Depth",
  "year": 2022
}